"use client";
import { motion } from "framer-motion";
export const MotionButtonHeader= motion.a;
export const MotionSpanHeaderHover= motion.span;
export const MotionDivExperienceCardHover= motion.div;
export const MotionSection= motion.section;
export const MotionDivSnake= motion.div;
export const MotionCarousel= motion.div;
export const MotionSkills= motion.div;
export const MotionSkillIcon= motion.div;
export const MotionSideNav= motion.div;